# Python Fundamentals

# Session 9

# Pandas Practice Task
---------------------------------------
Use the provided products.csv file.

1. Read the CSV file into a pandas DataFrame and print it.

2. Display the first 5 rows of the DataFrame.

3. Display the summary statistics of the DataFrame.

4. Display the data types of each column of the DataFrame.

5. Filter: Display only the products where Price > 5000 or Rating > 4.5

6. Sort: Sort the products by Price in descending order.

7. Handle Missing Values:
    1. Check for missing values in the DataFrame.
    2. Fill missing Price values with the average price.
    3. Fill missing Stock values with the average stock.

8. Add a new column: Add a column called In_Stock that is True if Stock > 0, otherwise False.

9. Add a new column: Add a column called Total_Value that contains Price * Stock.

10. Filter: Display products where Price > 3000 and Rating >= 4.0.

11. Aggregation: Calculate the average, minimum, and maximum Price, and total Stock.

12. Add a new column: Add a column called Price_Category:

    * Expensive if Price >= 10000
    * Medium if Price >= 3000
    * Cheap if Price < 3000

13. Rename a column: Rename Product_Name to Name.

14. Remove a column: Remove the Product_ID column from the DataFrame.

15. Drop Duplicates: Check for duplicate rows and remove them from the DataFrame.

16. Sort: Sort the products by Rating in descending order.

17. Save the modified DataFrame to a new CSV file called products_modified.csv.

In [22]:
import pandas as pd

1- Read the CSV file into a pandas DataFrame and print it.

In [23]:
df = pd.read_csv('products.csv')
df

    Product_ID  Product_Name     Category    Price  Stock  Rating
0          101        Laptop  Electronics  25000.0   15.0     4.6
1          102         Phone  Electronics  18000.0   30.0     4.3
2          103        Tablet  Electronics      NaN   20.0     4.7
3          104       Monitor  Electronics   8500.0    NaN     4.1
4          105      Keyboard  Accessories   1200.0   50.0     3.9
5          106         Mouse  Accessories    650.0   80.0     4.4
6          107       Printer       Office   5500.0   12.0     3.6
7          108       Headset  Accessories      NaN   35.0     4.8
8          109        Webcam  Accessories   2200.0   25.0     4.5
9          110       Speaker  Electronics   3000.0   40.0     4.0
10         111    Smartwatch  Electronics   7500.0   18.0     4.6
11         112     USB Cable  Accessories    300.0  100.0     3.8
12         113  External SSD      Storage   6500.0   22.0     4.7
13         114    Power Bank  Accessories   1500.0   60.0     4.2
14         115  Office Chair    Furniture   4500.0   10.0     4.1
15         115  Office Chair    Furniture   4500.0   10.0     4.1

2- Display the first 5 rows of the DataFrame.

In [24]:
df.head()

   Product_ID Product_Name     Category    Price  Stock  Rating
0         101       Laptop  Electronics  25000.0   15.0     4.6
1         102        Phone  Electronics  18000.0   30.0     4.3
2         103       Tablet  Electronics      NaN   20.0     4.7
3         104      Monitor  Electronics   8500.0    NaN     4.1
4         105     Keyboard  Accessories   1200.0   50.0     3.9

3- Display the summary statistics of the DataFrame.

In [25]:
df.describe()

       Product_ID         Price       Stock     Rating
count   16.000000     14.000000   15.000000  16.000000
mean   108.437500   6346.428571   35.133333   4.275000
std      4.661455   7041.974818   26.875019   0.356838
min    101.000000    300.000000   10.000000   3.600000
25%    104.750000   1675.000000   16.500000   4.075000
50%    108.500000   4500.000000   25.000000   4.250000
75%    112.250000   7250.000000   45.000000   4.600000
max    115.000000  25000.000000  100.000000   4.800000

4- Display the data types of each column of the DataFrame.

In [26]:
df.dtypes

Product_ID        int64
Product_Name     object
Category         object
Price           float64
Stock           float64
Rating          float64
dtype: object

5- Filter: Display only the products where Price > 5000 or Rating > 4.5.

In [27]:
df[(df['Price'] > 5000) | (df['Rating'] > 4.5)]

    Product_ID  Product_Name     Category    Price  Stock  Rating
0          101        Laptop  Electronics  25000.0   15.0     4.6
1          102         Phone  Electronics  18000.0   30.0     4.3
2          103        Tablet  Electronics      NaN   20.0     4.7
3          104       Monitor  Electronics   8500.0    NaN     4.1
6          107       Printer       Office   5500.0   12.0     3.6
7          108       Headset  Accessories      NaN   35.0     4.8
10         111    Smartwatch  Electronics   7500.0   18.0     4.6
12         113  External SSD      Storage   6500.0   22.0     4.7

6- Sort: Sort the products by Price in descending order.

In [28]:
df.sort_values(by='Price', ascending=False, inplace=True)

7- Handle Missing Values:

A- Check for missing values in the DataFrame.

B- Fill missing Price values with the average price.

C- Fill missing Stock values with the average stock.

In [29]:
df.isnull().sum()

Product_ID      0
Product_Name    0
Category        0
Price           2
Stock           1
Rating          0
dtype: int64

In [30]:
df['Price'].fillna(df['Price'].mean(), inplace=True)

C:\Users\engmo\AppData\Local\Temp\ipykernel_18916\3868442878.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price'].fillna(df['Price'].mean(), inplace=True)

In [31]:
df['Stock'].fillna(df['Stock'].mean(), inplace=True)

C:\Users\engmo\AppData\Local\Temp\ipykernel_18916\456429791.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Stock'].fillna(df['Stock'].mean(), inplace=True)

8- Add a new column:
Add a column called In_Stock that is True if Stock > 0, otherwise False.

In [32]:
df['In_Stock'] = df['Stock'] > 0
df['In_Stock']

0     True
1     True
3     True
10    True
12    True
6     True
14    True
15    True
9     True
8     True
13    True
4     True
5     True
11    True
2     True
7     True
Name: In_Stock, dtype: bool

9- Add a new column:
Add a column called Total_Value that contains Price * Stock.

In [33]:
df['Total_Value'] = df['Price'] * df['Stock']

10- Filter: Display products where Price > 3000 and Rating >= 4.0.

In [34]:
df[(df['Price'] > 3000) & (df['Rating'] >= 4.0)]

,Product_ID,Product_Name,Category,Price,Stock,Rating,In_Stock,Total_Value
0,101,Laptop,Electronics,25000.000000,15.000000,4.6,True,375000.000000
1,102,Phone,Electronics,18000.000000,30.000000,4.3,True,540000.000000
3,104,Monitor,Electronics,8500.000000,35.133333,4.1,True,298633.333333
10,111,Smartwatch,Electronics,7500.000000,18.000000,4.6,True,135000.000000
12,113,External SSD,Storage,6500.000000,22.000000,4.7,True,143000.000000
14,115,Office Chair,Furniture,4500.000000,10.000000,4.1,True,45000.000000
15,115,Office Chair,Furniture,4500.000000,10.000000,4.1,True,45000.000000
2,103,Tablet,Electronics,6346.428571,20.000000,4.7,True,126928.571429
7,108,Headset,Accessories,6346.428571,35.000000,4.8,True,222125.000000

11- Aggregation: Calculate the average, minimum, and maximum Price, and total Stock.

In [35]:
print(df['Price'].mean())
print(df['Price'].min())
print(df['Price'].max())
print(df['Total_Value'].mean())
print(df['Total_Value'].min())
print(df['Total_Value'].max())

6346.428571428572
300.0
25000.0
150230.43154761905
30000.0
540000.0

12- Add a new column:
Add a column called Price_Category:

Expensive if Price >= 10000

Medium if Price >= 3000

Cheap if Price < 3000

In [36]:
def price_tier(price):
    if price >= 10000:
        return 'Expensive'
    elif price >= 3000:
        return 'Medium'
    else:
        return 'Cheap'

df['Price_Tier'] = df['Price'].apply(price_tier)
df['Price_Tier']

0     Expensive
1     Expensive
3        Medium
10       Medium
12       Medium
6        Medium
14       Medium
15       Medium
9        Medium
8         Cheap
13        Cheap
4         Cheap
5         Cheap
11        Cheap
2        Medium
7        Medium
Name: Price_Tier, dtype: object

13- Rename a column:
Rename Product_Name to Name.

In [37]:
print(df.columns)
df.rename(columns={'Product_Name': 'Name'}, inplace=True)
print(df.columns)
df.head()

Index(['Product_ID', 'Product_Name', 'Category', 'Price', 'Stock', 'Rating',
       'In_Stock', 'Total_Value', 'Price_Tier'],
      dtype='object')
Index(['Product_ID', 'Name', 'Category', 'Price', 'Stock', 'Rating',
       'In_Stock', 'Total_Value', 'Price_Tier'],
      dtype='object')

,Product_ID,Name,Category,Price,Stock,Rating,In_Stock,Total_Value,Price_Tier
0,101,Laptop,Electronics,25000.0,15.000000,4.6,True,375000.000000,Expensive
1,102,Phone,Electronics,18000.0,30.000000,4.3,True,540000.000000,Expensive
3,104,Monitor,Electronics,8500.0,35.133333,4.1,True,298633.333333,Medium
10,111,Smartwatch,Electronics,7500.0,18.000000,4.6,True,135000.000000,Medium
12,113,External SSD,Storage,6500.0,22.000000,4.7,True,143000.000000,Medium

14- Remove a column:
Remove the Product_ID column from the DataFrame.

In [38]:
df.drop('Product_ID', axis=1, inplace=True)
df

,Name,Category,Price,Stock,Rating,In_Stock,Total_Value,Price_Tier
0,Laptop,Electronics,25000.000000,15.000000,4.6,True,375000.000000,Expensive
1,Phone,Electronics,18000.000000,30.000000,4.3,True,540000.000000,Expensive
3,Monitor,Electronics,8500.000000,35.133333,4.1,True,298633.333333,Medium
10,Smartwatch,Electronics,7500.000000,18.000000,4.6,True,135000.000000,Medium
12,External SSD,Storage,6500.000000,22.000000,4.7,True,143000.000000,Medium
6,Printer,Office,5500.000000,12.000000,3.6,True,66000.000000,Medium
14,Office Chair,Furniture,4500.000000,10.000000,4.1,True,45000.000000,Medium
15,Office Chair,Furniture,4500.000000,10.000000,4.1,True,45000.000000,Medium
9,Speaker,Electronics,3000.000000,40.000000,4.0,True,120000.000000,Medium
8,Webcam,Accessories,2200.000000,25.000000,4.5,True,55000.000000,Cheap
13,Power Bank,Accessories,1500.000000,60.000000,4.2,True,90000.000000,Cheap
4,Keyboard,Accessories,1200.000000,50.000000,3.9,True,60000.000000,Cheap
5,Mouse,Accessories,650.000000,80.000000,4.4,True,52000.000000,Cheap
11,USB Cable,Accessories,300.000000,100.000000,3.8,True,30000.000000,Cheap
2,Tablet,Electronics,6346.428571,20.000000,4.7,True,126928.571429,Medium
7,Headset,Accessories,6346.428571,35.000000,4.8,True,222125.000000,Medium

15- Drop Duplicates:
Check for duplicate rows and remove them from the DataFrame.

In [39]:
df.drop_duplicates(inplace=True)
df

,Name,Category,Price,Stock,Rating,In_Stock,Total_Value,Price_Tier
0,Laptop,Electronics,25000.000000,15.000000,4.6,True,375000.000000,Expensive
1,Phone,Electronics,18000.000000,30.000000,4.3,True,540000.000000,Expensive
3,Monitor,Electronics,8500.000000,35.133333,4.1,True,298633.333333,Medium
10,Smartwatch,Electronics,7500.000000,18.000000,4.6,True,135000.000000,Medium
12,External SSD,Storage,6500.000000,22.000000,4.7,True,143000.000000,Medium
6,Printer,Office,5500.000000,12.000000,3.6,True,66000.000000,Medium
14,Office Chair,Furniture,4500.000000,10.000000,4.1,True,45000.000000,Medium
9,Speaker,Electronics,3000.000000,40.000000,4.0,True,120000.000000,Medium
8,Webcam,Accessories,2200.000000,25.000000,4.5,True,55000.000000,Cheap
13,Power Bank,Accessories,1500.000000,60.000000,4.2,True,90000.000000,Cheap
4,Keyboard,Accessories,1200.000000,50.000000,3.9,True,60000.000000,Cheap
5,Mouse,Accessories,650.000000,80.000000,4.4,True,52000.000000,Cheap
11,USB Cable,Accessories,300.000000,100.000000,3.8,True,30000.000000,Cheap
2,Tablet,Electronics,6346.428571,20.000000,4.7,True,126928.571429,Medium
7,Headset,Accessories,6346.428571,35.000000,4.8,True,222125.000000,Medium

16- Sort:
Sort the products by Rating in descending order.

In [40]:
df.sort_values(by='Rating', ascending=False, inplace=True)
df

,Name,Category,Price,Stock,Rating,In_Stock,Total_Value,Price_Tier
7,Headset,Accessories,6346.428571,35.000000,4.8,True,222125.000000,Medium
12,External SSD,Storage,6500.000000,22.000000,4.7,True,143000.000000,Medium
2,Tablet,Electronics,6346.428571,20.000000,4.7,True,126928.571429,Medium
0,Laptop,Electronics,25000.000000,15.000000,4.6,True,375000.000000,Expensive
10,Smartwatch,Electronics,7500.000000,18.000000,4.6,True,135000.000000,Medium
8,Webcam,Accessories,2200.000000,25.000000,4.5,True,55000.000000,Cheap
5,Mouse,Accessories,650.000000,80.000000,4.4,True,52000.000000,Cheap
1,Phone,Electronics,18000.000000,30.000000,4.3,True,540000.000000,Expensive
13,Power Bank,Accessories,1500.000000,60.000000,4.2,True,90000.000000,Cheap
3,Monitor,Electronics,8500.000000,35.133333,4.1,True,298633.333333,Medium
14,Office Chair,Furniture,4500.000000,10.000000,4.1,True,45000.000000,Medium
9,Speaker,Electronics,3000.000000,40.000000,4.0,True,120000.000000,Medium
4,Keyboard,Accessories,1200.000000,50.000000,3.9,True,60000.000000,Cheap
11,USB Cable,Accessories,300.000000,100.000000,3.8,True,30000.000000,Cheap
6,Printer,Office,5500.000000,12.000000,3.6,True,66000.000000,Medium

17- Save the modified DataFrame to a new CSV file called products_modified.csv.

In [41]:
df.to_csv('products_modified.csv', index=False)

In [42]:
df_modified = pd.read_csv('products_modified.csv')
df_modified

,Name,Category,Price,Stock,Rating,In_Stock,Total_Value,Price_Tier
0,Headset,Accessories,6346.428571,35.000000,4.8,True,222125.000000,Medium
1,External SSD,Storage,6500.000000,22.000000,4.7,True,143000.000000,Medium
2,Tablet,Electronics,6346.428571,20.000000,4.7,True,126928.571429,Medium
3,Laptop,Electronics,25000.000000,15.000000,4.6,True,375000.000000,Expensive
4,Smartwatch,Electronics,7500.000000,18.000000,4.6,True,135000.000000,Medium
5,Webcam,Accessories,2200.000000,25.000000,4.5,True,55000.000000,Cheap
6,Mouse,Accessories,650.000000,80.000000,4.4,True,52000.000000,Cheap
7,Phone,Electronics,18000.000000,30.000000,4.3,True,540000.000000,Expensive
8,Power Bank,Accessories,1500.000000,60.000000,4.2,True,90000.000000,Cheap
9,Monitor,Electronics,8500.000000,35.133333,4.1,True,298633.333333,Medium
10,Office Chair,Furniture,4500.000000,10.000000,4.1,True,45000.000000,Medium
11,Speaker,Electronics,3000.000000,40.000000,4.0,True,120000.000000,Medium
12,Keyboard,Accessories,1200.000000,50.000000,3.9,True,60000.000000,Cheap
13,USB Cable,Accessories,300.000000,100.000000,3.8,True,30000.000000,Cheap
14,Printer,Office,5500.000000,12.000000,3.6,True,66000.000000,Medium